backend:
  name: git-gateway
  branch: main # Az ág, amelyet szerkeszteni fogsz

media_folder: static/images # A képek mentési helye
public_folder: /images # A képek elérési útvonala

collections:
  - name: "page"
    label: "Oldalak"
    folder: "src/pages"
    create: true
    fields:
      - { label: "Cím", name: "title", widget: "string" }
      - { label: "Tartalom", name: "body", widget: "markdown" }